twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
        - 'form/_fields.html.twig'
    paths:
        'assets/images': images
        'assets/styles': styles
